apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-wildcard
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  dnsNames:
  - '*.apps.cluster01.sharkbait.tech'
  - apps.cluster01.sharkbait.tech
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: cluster-wildcard-tls
