apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-argocd-integration
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: cluster-onboarding
    component: acm-argocd-integration
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: cluster-config
  source:
    repoURL: "git@github.com:atwin140/OCP-Cluster-config.git"
    targetRevision: HEAD
    path: components/acm-argocd-integration/base
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true
  revisionHistoryLimit: 10
