apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: cluster-onboarding
    component: keycloak-operator
    group.cluster: hub
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform-services
  source:
    repoURL: "git@github.com:atwin140/OCP-Cluster-config.git"
    targetRevision: HEAD
    path: components/keycloak-operator/overlays/hub
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  revisionHistoryLimit: 10
