apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: cluster-onboarding
    component: observability
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cluster-config
  source:
    repoURL: "git@github.com:atwin140/OCP-Cluster-config.git"
    targetRevision: main
    path: components/observability/overlays/hub
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true
  revisionHistoryLimit: 10
