apiVersion: v1
kind: ConfigMap
metadata:
  name: acs-declarative-auth
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  auth-provider.yaml: |+
    name: "OpenShift Authentication"
    minimumRole: "Analyst,Admin"
    uiEndpoint: "central-stackrox.apps.acm.sharkbait.tech"
    openshift:
      enable: true
    groups:
    - key: "groups"
      value: "system:cluster-admins"
      role: "Admin"
      
