apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- keycloak-group-sync.yaml
- ocp-oauth.yaml
# - compliance-operator.yaml
# - observability.yaml
- cert-manager.yaml

# - gitea.yaml
