apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: cluster-onboarding
    component: sealed-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: cluster-config
  source:
    repoURL: "git@github.com:atwin140/OCP-Cluster-config.git"
    targetRevision: main
    path: components/sealed-secrets/overlays/all
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
  revisionHistoryLimit: 10
