apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: cluster-onboarding
    component: network-policies
    group.region: east
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cluster-config
  source:
    repoURL: "git@github.com:atwin140/OCP-Cluster-config.git"
    targetRevision: HEAD
    path: components/network-policies/overlays/east
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-network-policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  revisionHistoryLimit: 10
