apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
namePrefix: hub-

resources:
- ../../../groups/all
- ../../../groups/hub
# - ../../../groups/east
# - ../../../groups/non-prod

patches:
- path: patch-destination-server.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application

# Uncomment this patch block to disable Argo CD auto-sync again.
# - path: patch-disable-autosync.yaml
#   target:
#     group: argoproj.io
#     version: v1alpha1
#     kind: Application

- path: patch-cert-manager-source.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: cert-manager

- path: patch-observability-source.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: observability
