apiVersion: v1
kind: Secret
metadata:
  name: hub-keycloak-realm-config
  namespace: keycloak
type: Opaque
stringData:
  # Must match openshift-config/keycloak-oidc-client-secret:clientSecret
  clientSecret: CHANGE_ME
  # OCP callback URL for this cluster.
  redirectUri: https://oauth-openshift.apps.acm.sharkbait.tech/oauth2callback/keycloak
  # Web origin for the OIDC client.
  webOrigin: +
