apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: keycloak-groupsync
  namespace: group-sync-operator
spec:
  schedule: "*/15 * * * *"
  providers:
  - name: keycloak
    keycloak:
      url: https://keycloak.apps.acm.sharkbait.tech
      realm: openshift
      loginRealm: openshift
      scope: sub
      prune: false
      credentialsSecret:
        name: keycloak-group-sync
        namespace: group-sync-operator
      ca:
        kind: ConfigMap
        name: keycloak-certs
        namespace: group-sync-operator
        key: ca.crt
      groups:
      - openshift-access
