apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-keycloak-credentials-secret.yaml
  - 10-keycloak-ca-configmap.yaml
  - 20-groupsync.yaml
  - 30-cluster-admin-binding.yaml
