apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
namePrefix: cluster01-

resources:
- ../../../groups/all
# - ../../../groups/east
# - ../../../groups/non-prod

patches:
- path: patch-destination-server.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
