apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - keycloak-oidc-client-secret.yaml
- oauth-cluster.yaml

commonLabels:
  app.kubernetes.io/part-of: ocp-oauth
  app.kubernetes.io/managed-by: argocd
