apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- multicluster-observability.yaml
- mco-addon.yaml
- datasource.yml
- perses-dashboards/acm-multicluster-fleet-overview.yaml
- perses-dashboards/acm-multicluster-workload-health.yaml
- perses-dashboards/acm-multicluster-control-plane-etcd.yaml

commonLabels:
  app.kubernetes.io/part-of: multicluster-observability
  app.kubernetes.io/managed-by: argocd
