apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  observabilityAddonSpec:
    enableMetrics: true
    interval: 300
    workers: 1
    scrapeSizeLimitBytes: 1073741824
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml