apiVersion: v1
kind: Secret
metadata:
  name: perses-sa-bearer
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  token: |
    authorization:
      type: Bearer
      credentialsFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
