---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-object-storage
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  encryptedData:
    thanos.yaml: ##removed
  template:
    metadata:
      name: thanos-object-storage
      namespace: openshift-cluster-observability-operator
    type: Opaque
