apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-acs-manager
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups:
  - platform.stackrox.io
  resources:
  - centrals
  - centrals/status
  - centrals/finalizers
  - securedclusters
  - securedclusters/status
  - securedclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
