# West cluster network-policies overlay.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-network-policies

commonAnnotations:
  cluster.name: west
  cluster.region: us-west-2

resources:
- ../../base
