apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  observabilityAddonSpec:
    enableMetrics: true
    interval: 300
    workers: 1
    scrapeSizeLimitBytes: 1073741824
  storageConfig:
    storageClass: nas-iscsi-ext4-vol2
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
