apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hub-keycloak
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  to:
    kind: Service
    name: hub-keycloak-service
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
